name: CI
description: "Main CI action for merit-activa-js"
on:
  push:
    branches:
      - "**"
runs:
  using: 'node20'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Builds merit-activa-js
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
